### ISSUE TITLE
See if we can somehow use .gitignore

### ISSUE THREAD

**Issue by petdance** [petdance/ack2#28]
I don't think we want to use .gitignore automatically, but maybe in ack 2.1 we can do something like add a --ignorefile=.gitignore.

**Comment by sheerun** [comment]
+1 `--ignore-dir` entires in ackrc grow larger and larger, because I can't simply ignore what's in gitignore

**Comment by hoelzro** [comment]
Thanks everyone for chiming in.  ack2 is in a bit of a code freeze at the moment; @petdance would like to go through everything that's changed since 2.14 so that 2.16 can be released, and we don't want to heap any more work on at the moment.  If anyone is willing to submit a pull request implementing the feature, however, we can merge it in once 2.16 is released!

**Comment by petdance** [comment]
Does anyone know how Windows Git does .gitignore?

**Comment by petdance** [comment]
.gitignore is all globs, right?  The .gitignore would be the only place that ack handles globs.

Does anyone know how Windows Git does .gitignore?

Handling .gitignore is not a CYJ.  (Can't you just...)

**Comment by hoelzro** [comment]
I don't know for sure, but I'm guessing that gitignore on Windows works pretty much the same as on OS X/Linux, maybe with some accounting for case insensitivity.

.gitignore can contain more than just globs; you can have inverted expressions (ex. ignore all `.jar` files, except for those under `deps`), or relative paths (ex. ignore all jars in `/.mvn` or something).  Absolute paths introduce an especially sinister level of complexity, since they're absolute with respect to the root of the working tree.  Which means we would have to detect the root of the working tree, which means respecting `GIT_WORK_TREE` and `GIT_DIR`.  And let's not forget that there's not just one gitignore file; you have `.gitignore`, `$GIT_DIR/info/exclude`, the config setting `core.excludesfile`, and anything else I forgot to mention.  Long story short, that would be a *lot* of git implementation details to put into ack, and frozen to which ever version's implementation we would port over.

That being said, we could shell out to `git ls-files`, but then we have to handle the case where someone doesn't have git installed, or isn't in a git repository, and reconcile potential differences between versions of Git.  So even that route is frought with peril.

My suggestion is this:  if you really want this feature, write a shell wrapper around `ack` to call `git ls-files` and populate `ACK_OPTIONS` based on its output, and then call `ack`.  If we end up implementing this feature, it probably won't be for a while.

**Comment by SethTisue** [comment]
fwiw, from issues like e.g. https://github.com/ggreer/the_silver_searcher/issues/100 it appears the ag folks went the route of parsing `.gitignore` themselves (apparently imperfectly)

**Comment by Nolski** [comment]
Well this is unfortunate. This bug is the reason that I'll be switching to ag.

**Comment by pmorch** [comment]
Perhaps one way to achieve this without supporting `.gitigore` directly in `ack` could be to write a script that generates a `$PROJECT/.ackrc` from all the `.gitignore` files (and whatnot) in the project.

Probably not trivial to write if all the corner cases must be supported. @hoelzro [wrote](https://github.com/petdance/ack2/issues/28#issuecomment-70696864):

> And let's not forget that there's not just one gitignore file; you have .gitignore, $GIT_DIR/info/exclude, the config setting core.excludesfile, and anything else I forgot to mention.

This would certainly scratch my itch right now:

    cd $PROJECT
    $ACK/contrib/generate-ackrc-from-gitignore.pl . > .ackrc
    ack pattern
Also, then it isn't baked directly into `ack`.

**Comment by naggie** [comment]
`alias gack="git ls-files -oc --exclude-standard | ack -x"` is what I use.

**Comment by petdance** [comment]
Does my heart good to see people using `ack -x`.

**Comment by petdance** [comment]
I don't want ack to have to dig into .gitignore files, but we can put the git line in the docs.

**Comment by naggie** [comment]
Good idea, I agree with you that ack should not parse .gitignore files.

One caveat with that alias is that submodules are listed by the git command and they are directories -- ack then (correctly) complains about the directories.


With git 2.11+, the `--recurse-submodules` option may be used which should work around this, and of course match files within submodules which might not be desired.


Here's the same command with the long options which are semantic so better for docs:
```
alias gack="git ls-files --others --cached --exclude-standard | ack -x"
```

**Comment by petdance** [comment]
We are not going to parse .gitignore.

**Comment by petdance** [comment]
This issue was moved to petdance/ack3#40

**Comment by dboehmer** [comment]
Because you’re going to use this only inside a Git repo you can also make it a Git alias similar to the built-in `git grep`:

```
git config --global alias.ack '! git ls-files --others --cached --exclude-standard | ack -x'
git ack foo
```

**Comment by petdance** [comment]
That's pretty slick.  I might have to put that in the docs somewhere.
