### ISSUE TITLE
Lookbehind sometimes causing wrong part of line to be highlighted

### ISSUE THREAD

**Issue by mikez302** [petdance/ack2#374]
I am running ack 2.08 on OS X 10.8.4. If I run `echo 'xy' | ack '(?<=x)y'` from the terminal, it prints `xy` with the y highlighted, like I would expect. But if I run `echo 'xy' | ack '(?<=(x))y'`, then it prints `xy` with the x highlighted. Is this intended behavior or a bug? I would think the y is the actual match and the x is not part of it. The grouping should have nothing to do with it.

**Comment by n1vux** [comment]
Yes, Andy has said elsewhere that he considers highlighting `$1` from capturing parens instead of always highlighting `$&` to be a known bug in ack2, which will be fixed in ack3 .  

This also means `ack2 'x(y)'`  will highlight the same as `ack2 '(?<=x)y'` ( but it won't in ack3 ). 

The workaround for now is as @packy notes to use non-capturing parens `(?:...)` if you need parens but don't want to focus the highlight there.

**Comment by petdance** [comment]
This is fixed in ack 3.  I'm leaving the feature in ack 2 as-is.
