### ISSUE TITLE
-bash: ack-grep: command not found

### ISSUE THREAD

**Issue by kenorb** [petdance/ack2#553]
I've installed ack using `brew install ack` on OS X 10.9.5, however I've the following error:

    -bash: ack-grep: command not found

I've checked the script, but actually nowhere it refers to `ack-grep`, apart of the comments. Is something is broken, or I should do some symbolic linking manually?

**Comment by xtaran** [comment]
`ack-grep` was/is the name of the binary and package of Ack in older Debian releases and Debian derivatives (like Ubuntu) because there was already a Kanji converter called `ack` in Debian. (That one's now gone making space for Ack's real name.) That name is not used by Ack itself (except in the FAQ) and hence shouldn't appear anywhere outside Debian and derivatives.

**Comment by kenorb** [comment]
I've actually found that running `\ack` (or `perl /usr/local/bin/ack`) worked as normal.

So actually the problem was with aliases in my `~/.bash_aliases`:

    alias {ack,ak}='ack-grep'

I must copied it from somewhere else.

Removing it solved the problem. Thanks for your help.
