### ISSUE TITLE
please support --markdown

### ISSUE THREAD

**Issue by paul-hammant** [petdance/ack2#593]
you know, like --python, etc

**Comment by afeld** [comment]
I'd still like to see this 😄

**Comment by petdance** [comment]
What extensions would that include?

**Comment by afeld** [comment]
`.md` and `.markdown` are the most common, though [there are others](https://superuser.com/a/285878).

**Comment by petdance** [comment]
> there are others.

Which is why I asked my question.

What extensions are you using for Markdown in your .ackrc?

**Comment by afeld** [comment]
https://superuser.com/questions/249436/file-extension-for-markdown-files/285878#285878

has an exhaustive list, but `.md` and `.markdown` ([in that order of prevalence](https://talk.commonmark.org/t/file-extension-for-commonmark/440/6)) are the only ones I've seen in the wild. Thanks for reopening!

**Comment by petdance** [comment]
That exhaustive list could be listing everything everyone has ever come up with, so it's hard to put much credence into it.

What are you using in your .ackrc?

**Comment by afeld** [comment]
```
$ cat ~/.ackrc | grep md
--type-add=markdown=.md,.markdown
--type-add=md=.md,.markdown
```

**Comment by petdance** [comment]
Why two different types?

**Comment by xtaran** [comment]
I've seen `.mdwn` in the wild, too. And I use it myself occassionally because `.markdown` is too long for my tastes (especially for README files) and depending on the context `.md` can be ambiguous.

Real life case where someone was unhappy about the `.md` suffix: I named a file `README.md` in a context of a tool working in file systems in the farest sense and since Linux Software RAID is also known as "MD RAID", [someone filed a bug report](https://bugs.debian.org/678630) that this file name is misleading. Solved that case differently, though, by dropping the suffix completely upon deployment...

**Comment by petdance** [comment]
I'm leaning toward .md and .markdown because they seem like the least worst options.

**Comment by paul-hammant** [comment]
Agree with  .md and .markdown :)

**Comment by petdance** [comment]
This will happen in ack3: https://github.com/petdance/ack3/issues/62

**Comment by petdance** [comment]
This is now done in ack3. 519a577
