### ISSUE TITLE
Add docs on how to make grep look like ack

### ISSUE THREAD

**Issue by petdance** [petdance/ack2#619]
I think a lot of people use ack strictly because of the grouping and the pretty colors.  It's trivial to make grep do this and then you don't have to use ack.

Put something in the ack docs that explains how.

**Comment by packy** [comment]
I'm just commenting in here as I find things:

- turning on color highlighting of matches: `export GREP_OPTIONS='--color=auto'` (alternately, I use `alias grep='grep --color=auto'`)

- set grep matching color to black text on yellow background: `export GREP_COLOR='30;43'` (colors are the same ones as documented for [ANSI/VT100 Escape Sequences](http://www.termsys.demon.co.uk/vtansi.htm#colors))

- turn on line numbers for matches: `export GREP_OPTIONS='--line-number'`

- always print filename headers with output lines: `export GREP_OPTIONS='-H'`

I know this doesn't do the grouping, but I think I'll need to do a bash function for that.

**Comment by n1vux** [comment]
GNU doesn't want to make it easy.
While yes one could export
`GREP_OPTIONS=-R`
but they'll warn because that is deprecated as non-portable. *sigh*
https://www.gnu.org/software/grep/manual/html_node/Environment-Variables.html#Environment-Variables
​They say " Please use an alias or script instead", which means to make grep work differently you have to rename the new behavior.

**Comment by petdance** [comment]
This issue was moved to petdance/ack3#30
